### ISSUE TITLE
usage of 

### ISSUE THREAD

**Issue by qsh-zh** [phizaz/diffae#12]
I am a bit confused by args passed to resnet, https://github.com/phizaz/diffae/blob/master/model/blocks.py#L196-L211

```
    def _forward(
        self,
        x,
        emb=None,
        cond=None,
        lateral=None,
    ):
```

where `emb` is time embedding, `cond` is for semantic code, but what is usage of `lateral`?

**Comment by phizaz** [comment]
Lateral is part of the legacy code and should not be used. Sorry for the confusion.

**Comment by qsh-zh** [comment]
Thanks for your timely response
