### ISSUE TITLE
Inference DiffAE as AutoEncoder

### ISSUE THREAD

**Issue by koda12344505** [phizaz/diffae#13]
Hi, thank you for sharing this nice works.

Can you share some example code for how to use DiffAE as auto encoder?

some .ipynb file would be great.

thanks.

**Comment by phizaz** [comment]
Added in https://github.com/phizaz/diffae/commit/c5e2208a0f61fad4cfff7714485a7951c04b918a. See `autoencoding.ipynb`.

**Comment by koda12344505** [comment]
Thank you!
