### ISSUE TITLE
torchmetrics version

### ISSUE THREAD

**Issue by TheFrok** [phizaz/diffae#14]
The pytorch lightning package doesn't require a specific version of torchmetrics,
This causes import errors since torchmetrics moves classes around.

The ligthning version specified in requirements.txt works with torchmetrics==0.6.2

**Comment by TheFrok** [comment]
Yes exactly.
The right solution for that would be to change the requirements of pytohrch
lightning
But since you work with a specific version of lightning even if they'll
patch that it won't affect you.

**Comment by phizaz** [comment]
Fixed in https://github.com/phizaz/diffae/commit/f3d3e5555fccf69cbf6fbb62ed24a09894a0d5a2. I used `torchmetrics==0.5.0` as in the development environment.

**Comment by TheFrok** [comment]
Thanks!
