### ISSUE TITLE
How to eval the model?

### ISSUE THREAD

**Issue by koda12344505** [phizaz/diffae#15]
Hi, do you have a plan to release evaluation code?

or can you explain how to eval the model?

**Comment by phizaz** [comment]
I believe it is in the code base already. See https://github.com/phizaz/diffae/blob/d961b172df3064f7069d97d9992694352583999c/run_ffhq128_ddim.py#L10 and https://github.com/phizaz/diffae/blob/d961b172df3064f7069d97d9992694352583999c/run_ffhq128.py#L26. After running the aforementioned lines of code, you will get the FID numbers useful for comparing across generative models.
