### ISSUE TITLE
EMA model lagging behind

### ISSUE THREAD

**Issue by matanat** [phizaz/diffae#16]
Thanks so much for awesome work!
After around 1 Million images my model samples already look pretty good, but the ema samples are still very noisy (FID of 450 vs. 76). Does this make sense? 
I thought in general the ema model is supposed to have better and more stable results.

**Comment by phizaz** [comment]
It makes sense. One million images are only ~8000 iterations with 128 batch size. This still leaves traces of initial weights on the EMA model, not long enough for it to reach a sensible region of weights.

**Comment by zengxianyu** [comment]
Is this because the ema decay factor is too small for fp16 precision? when doing ema the target model precision is also fp16 and the default ema decay factor is 0.9999

**Comment by zengxianyu** [comment]
could this be related to fp16 precision training?
