### ISSUE TITLE
stochastic subcode xT

### ISSUE THREAD

**Issue by betterze** [phizaz/diffae#17]
Dear diffae group,

Thank you for sharing this great work. 

In section 3.1, you mention that 'for training, the stochastic subcodexT is not needed.' You mean X_T is freezed during training? From time T to T-1, we need to have X_T according to equation 6, right? 

Thank you for your help.

Best Wishes,

Zongze

**Comment by phizaz** [comment]
Oh, not like that. 

Allow me to make the jargon a bit clearer. **Stochastic subcode**, `X_T`, is meant to be the "inverted noise". To get this, you need an original image, `X_0`, and run the denoising process backward effectively adding noise to the image (see DDIM paper for more details). Repeating this for T steps, you'll get the "exact" `X_T` that corresponds to that original image, `X_0`. 

Not to be confused with a "usual" X_T which all you need is just scaling down the RGB and adding some noise. This usual noise is not specific to the original X_0 while the stochastic subcode, acting as a latent code, is specific to the original image.  

Training diffusion autoencoders don't need the stochastic subcodes that are costly to get. You only need the cheap usual X_T's. Training DiffAE's hence are just like any other DPMs. The changes are only on the architecture and on what is supplied to it. Only when you need to get the best quality reconstruction of the original image, you need to obtain the stochastic subcode, not during training.

**Comment by betterze** [comment]
Thx a lot. I understand it now.
