### ISSUE TITLE
Request for Download Link

### ISSUE THREAD

**Issue by TwistedAlex** [phizaz/diffae#18]
Hi,
Could you please provide the download link for DiffAE (with latent DPM, can sample): [FFHQ256]? Just like the links you provided in the DiffAE Manipulation demo for Colab (simplified version).ipynb.
Thank you!

**Comment by phizaz** [comment]
Actually, the links are already provided in the readme. I suspect that what you really want is an example code for sampling from FFHQ256 model. I've updated the `sample.ipynb` in https://github.com/phizaz/diffae/commit/6328174152cfa3361877ca61cb629aeab1b7f319.
