### ISSUE TITLE
Missing evaluate_interpolate_fid

### ISSUE THREAD

**Issue by Gorluxor** [phizaz/diffae#2]
In experiment.py in the function `intp_fid` the `evaluate_interpolate_fid `method is called which doesn't exist in the publicly available repo, alongside the error that will be thrown because `.is_interpolate()` is not part of `TrainMode` class. Guess this was not intended. 
Adding `def is_interpolate(self):  return None` does fix the problem of the run error, but putting it out here.

**Comment by phizaz** [comment]
Can you point out which training pipeline you encountered this error?

**Comment by phizaz** [comment]
Removed interpolate fid in https://github.com/phizaz/diffae/commit/959aa82b48f319be01899eb5ee48e284f28cb854.

**Comment by Gorluxor** [comment]
> Can you point out which training pipeline you encountered this error?

Its on a ffhq64 based on celeba64, using the predefined autoenc ffhq settings before 128, with adding a very large batch size (256 * 4 gpus or 8 gpus). 

But as you already fixed it, I think it pops up generally.
