### ISSUE TITLE
Total training time

### ISSUE THREAD

**Issue by Etzelkut** [phizaz/diffae#28]
Hello,
Thank you for your work!
However, it was not clear from the paper how much time it took for the model(s) to be trained. Is it in countable (on average) in days or just hours (took less than a day)?

**Comment by phizaz** [comment]
This information is in the supplementary material. 
You can see the throughput (imgs/gpu/sec) here:
![image](https://user-images.githubusercontent.com/451667/187002141-7a57e327-e45d-4936-a0a3-0e8eb7f309cd.png)

**Comment by Etzelkut** [comment]
Thanks a lot! So if my understanding and calculation are close to correct, then training could take a little under a week for FFHQ-128 with 4 V100, and with a larger dataset, it could span several weeks. Am I correct?

**Comment by phizaz** [comment]
That seems right. However, larger datasets don't necessarily take more time to train, at least not likely in proportion to the size of the dataset. You need a certain number of images, aka. iterations (not unique images) to get a certain quality of diffusion model. It's unlikely that double the dataset size would take 2x more time to train. Besides, you may decide to end the training whenever the quality is acceptable. You may set a fixed number of images like 100M regardless of the number of image in the dataset.

**Comment by Etzelkut** [comment]
Thanks, I see now! This is not an easy task to train such models in terms of time and computing, so hoping that in future some possible research in the area of efficiency will pop up :)
