### ISSUE TITLE
About the peformance of running "sbatch run_ffhq256.py"

### ISSUE THREAD

**Issue by jingyang2017** [phizaz/diffae#29]
Thanks for the excellent work. 
I have tried to run sbatch run_ffhq256.py with 1 node 8 GPUS. 
In comparison to the released model [last.ckpt](https://vistec-my.sharepoint.com/personal/nattanatc_pro_vistec_ac_th/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fnattanatc%5Fpro%5Fvistec%5Fac%5Fth%2FDocuments%2Fdiffae%2Dpublic%2Fcheckpoints%2Fffhq256%5Fautoenc&ga=1)
I found some differences in performance.

My evalution code was based on https://github.com/phizaz/diffae/blob/master/autoencoding.ipynb with a change in how to get XT.
```
xT = torch.randn(len(cond),3,conf.img_size,conf.img_size,device=cond.device)
```

For the released model, I got:
![image](https://user-images.githubusercontent.com/33462014/187409698-3f2b0a7c-5631-4d17-bbb4-7de74a400d9d.png)

For my training model, I got
![image](https://user-images.githubusercontent.com/33462014/187410549-f2537b41-e17f-4fab-8e8d-3d856a5c94c5.png)

The difference is even larger when I test both in other images (different dataset)

For the released model, I got:
![image](https://user-images.githubusercontent.com/33462014/187411022-191405ce-6c8c-4058-9757-221a8765b2e1.png)

For my training model, I got
![image](https://user-images.githubusercontent.com/33462014/187410848-c856149d-e7bc-4a01-95d5-cde5a44cdf73.png)

It shows the released model is very robust in different situations but not for my version.

Did I mistake anything in code?

**Comment by phizaz** [comment]
The first question is how many images the model has been trained? The released mode was trained on 90M images. This could easily be the largest difference.

**Comment by jingyang2017** [comment]
> The first question is how many images the model has been trained? The released model was trained on 90M images. This could easily be the largest difference.

Thanks for your reply. I used this https://drive.google.com/drive/folders/1ww7itaSo53NDMa0q-wn-3HWZ3HHqK1IK to train. Is it correct?

**Comment by jingyang2017** [comment]
I trained about 3 days with 8 GPUS 1 node. The last image printed in checkpoint is 10000000.png. I  only changed the data path, 2node->1 node, [0,1,2,3]->[0,1,2,3,4,5,6,7] in this code. The parameter for images trained: conf.total_samples = 200_000_000, conf.batch_size = 64. When I open the donwloaded data ffhq256.lmdb, its length is 70001.

**Comment by jingyang2017** [comment]
> Sorry for misunderstanding. I believe that there is nothing wrong with your dataset. My question was how long did you train your models, how large is your (iterations * batch size, aka. number of images trained) ?

I trained about 3 days with 8 GPUS 1 node. The last image printed in checkpoint is 10000000.png. I only changed the data path, 2node->1 node, [0,1,2,3]->[0,1,2,3,4,5,6,7] in this code. The parameter for images trained: conf.total_samples = 200_000_000, conf.batch_size = 64. When I open the donwloaded data ffhq256.lmdb, its length is 70001.

**Comment by phizaz** [comment]
10,000,000 is far too early to get a good model. The quality is nowhere near saturation. You'll start to see reasonable results around 72M (million).

**Comment by jingyang2017** [comment]
> 10,000,000 is far too early to get a good model. The quality is nowhere near saturation. You'll start to see reasonable results around 72M (million).

Thanks for your reply. I will extend the training steps.
