### ISSUE TITLE
A question about add z_sem add to conditional ddim

### ISSUE THREAD

**Issue by Allencheng97** [phizaz/diffae#31]
Dear diffae team,

Thank you for your great work.  I have one question about some implementation detail.
 I am wondering how do you add the encoded z_sem into the conditional DDIM? 
![image](https://user-images.githubusercontent.com/47037416/189506174-d7e7948e-0052-47dd-a037-39fb6835f469.png)
1.Is it mean first feed the z_sem into a linear layer to change its shape then use it to multiply (the bottleneck output+timestep embedding)?

![image](https://user-images.githubusercontent.com/47037416/189506404-5e92d913-8d61-4651-b262-684cce074f3b.png)
2.Or it is concat(output,z_sem) like cGAN do? 
3.If it is not the case 2, what are concat in the middle?
I read the code and try to find where you define the model.render function and which part of code does this work but I didn't find it.
I will appreciate if you could kindly let me where is this code.

Best Regards

**Comment by phizaz** [comment]
The misunderstanding probably comes from Figure 8, which is the description of "latent" DDIM. There, "concat" has nothing to do with conditioning. It is there as a kind of "skip connection" for the latent DDIM network only, i.e., you won't see this in the main image producing UNET model. 

Where is it in the code?
It's in `blocks.py` in `ResBlock`'s forward:
https://github.com/phizaz/diffae/blob/865f1926ce0d994e4a8dc2b5b250d57f519cadc1/model/blocks.py#L222
and `apply_condition` function:
https://github.com/phizaz/diffae/blob/865f1926ce0d994e4a8dc2b5b250d57f519cadc1/model/blocks.py#L260

It's not as nice to read as I'd hope. I'm sorry for this. 
The overall idea, I think, is close to your 1). 

The actual line is https://github.com/phizaz/diffae/blob/865f1926ce0d994e4a8dc2b5b250d57f519cadc1/model/blocks.py#L323.
```
for i, (scale, shift) in enumerate(scale_shifts):
        # if scale is None, it indicates that the condition is not provided
        if scale is not None:
            h = h * (biases[i] + scale)
            if shift is not None:
                h = h + shift
```

Let `h` be the image features of shape `(n, c, h, w)`.
You first add and multiply `h` channel-wise with the transformed conditions from time embeddings, and keep it as `h`.
Second, you only multiply `h` channel-wise with the transformed conditions from the `z_sem`.

**Comment by Allencheng97** [comment]
Thank you very much for your clear and prompt reply!
