### ISSUE TITLE
Question about using the Latent DDIM to Generate $z_{sem}$

### ISSUE THREAD

**Issue by tomtom1103** [phizaz/diffae#42]
Hello DiffAE team, thank you for this work. It's absolutely amazing.
I've been playing around with the codebase, and seem to be lost with how to generate the latent z_sem on its own.

I've been using the third checkpoint FFHQ256:

>DiffAE (with latent DPM, can sample): [FFHQ256](https://vistec-my.sharepoint.com/:f:/g/personal/nattanatc_pro_vistec_ac_th/EtYAk4GzroFFv0yxG-YOM4MBhA2i_e_RYpOHYyrcziZHIQ?e=EGxBnQ)

and seem to be a bit lost with how the LiT module operates. If I'm not mistaken, this checkpoint should allow sampling z_sem directly, like how an image is sampled unconditionally in a vanilla DPM, but can't seem to find the right method to call.

Also, this checkpoint should allow to call upon the `model.render()` function, but I'm hit with the `NotImplementedError`.

Am I not getting something right with the module itself? It would be great if I could just call `conf = ffhq256_autoenc_latent()
` upon the model and sample z_sem directly, and also play around with the `model.render()` function.

Any type of help would be much appreciated.

Cheers,

Tom

**Comment by phizaz** [comment]
Have you tried `sample.ipynb`? The correctly loaded model should support `moder.render()` call.

**Comment by tomtom1103** [comment]
sorry for the late response, turns out I was just unfamiliar with the codebase. Again, thank you for your work!
