### ISSUE TITLE
network architecture 

### ISSUE THREAD

**Issue by betterze** [phizaz/diffae#5]
Dear Diffae team,

Thank you for sharing this great work, I really enjoy it. 

I understand that the Unet architecture  you used is based on [guided diffusion model](https://github.com/openai/guided-diffusion). Unfortunately, they do not provide a figure to visualize the network architecture, it is very hard for me to understand its architecture. Would you mind providing a figure to explain the structure of the Unet you used? From the codes, the Unet seems to contain 3 blocks (input, middle, output).

Thank you for your help.

Best Wishes,

Zongze

**Comment by phizaz** [comment]
I understand that the Unet could be quite complicated. I still have the feeling of trying to figure it out line-by-line the first time I laid my hands on it. However, I do not have the bandwidth to do the visualization for you. I also forgot a large part of it as well. Sorry for this.

**Comment by betterze** [comment]
Thx a lot for your reply. I really appreciate it.
