### ISSUE TITLE
Configuration of the experiment -- attribute manipulation on real images

### ISSUE THREAD

**Issue by david20571015** [phizaz/diffae#65]
Thanks for your outstanding work!

I have a question regarding the computation of FID for attribute manipulation, specifically referring to Section 5.3 and Appendix G in your paper.

From my understanding, the procedure is as follows:
1. Find the median confidence score for real positive images in *CelebA-HQ* (since there are no labels in FFHQ).
2. Manipulate the images of *CelebA-HQ* and *FFHQ* (about 30000+70000 images)
3. Compute the FID between manipulated images (from 2.) and real positive images of *CelebA-HQ*
4. Compute the FID between manipulated images (from 2.) and real negative images of *CelebA-HQ*
and all images are 256*256.

I would like to confirm if my understanding is correct.

**Comment by phizaz** [comment]
It has been some time. This is what I recall.
1. Correct.
2. Only CelebA-HQ
3. Correct.
4. No, it's between real positive and real negative. This serves as a baseline distance.

The goal is to show that real positive and manipulated positive is relatively close, but it's hard to show without a baseline. So we have a baseline between real positive and real negative (and we hope that we can get smaller than that number).

**Comment by david20571015** [comment]
Thank you for your response and corrections. I now figure it out.

**Comment by david20571015** [comment]
Sorry to bother you @phizaz. If it's convenient, could you please answer the question I mentioned earlier, thanks you!
