### ISSUE TITLE
Inquiry about using Guided-Diffusion parameters 

### ISSUE THREAD

**Issue by liutaocode** [phizaz/diffae#68]
Hello diffae team,

Thanks for your great work~!

I would like to ask if you have imported any pre-trained parameters related to guided-diffusion when training the auto-encoder network, like FFHQ? Or did you start training from scratch? Thank you very much for your answer.

Thanks.

**Comment by phizaz** [comment]
Everything is trained from scratch.

**Comment by liutaocode** [comment]
Understood~
Thanks for your quick response.
