### ISSUE TITLE
Regarding the error I met when I try to run the run_bedroom128.py

### ISSUE THREAD

**Issue by Vummal** [phizaz/diffae#71]
Hi,

When I try to run the bedroom code, I met some errors. The first time I met the problem in Epoch 40. It shows ''RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory''. And then the code stopped. I have attached the screenshots. If you could provide some help, I will be very appreciated. 
![Screenshot from 2023-12-11 14-19-11](https://github.com/phizaz/diffae/assets/95183652/769ae4fb-2980-4620-8812-b1d2acdeea26)

**Comment by phizaz** [comment]
Looks like either the pytorch version that you use doesn't match or the checkpoint file is corrupted.

**Comment by Vummal** [comment]
Thanks for your help. I have solved the problem I met before. However, when I train the latent DPM, I met some errors. It showed **RuntimeError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '1', but store->get('1') got error: Socket Timeout.** 

And some other errors are **[E ProcessGroupNCCL.cpp:474] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1132, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800188 milliseconds before timing out.

[E ProcessGroupNCCL.cpp:488] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.      | 0/157 [00:00<?, ?it/s]
[E ProcessGroupNCCL.cpp:494] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:915] [Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1132, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800188 milliseconds before timing out.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1132, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800188 milliseconds before timing out.
**
I ran the code on two RTX A6000s. I am wondering if you met these errors before. If you could give me some advice, you will be very appreciated.

**Comment by phizaz** [comment]
The problem you encountered here is due to parallel training which isn't at all needed to train the latent DPM, which wasn't designed to be trained parallelly in the first place. Please try training the latent DPM with a single GPU, and it won't take that long in the first place.

**Comment by Vummal** [comment]
Thanks for your help. The problem has been solved.
