### ISSUE TITLE
Difference in Model Weights

### ISSUE THREAD

**Issue by aashishrai3799** [phizaz/diffae#72]
Hi,

I was wondering why there are differences in the autoencoder weights used in autoencoder.ipynb and sample.ipynb. The former has a size of 2.7GB, while the latter is 2.2GB. Also, if I load the autoencoder weights used in autoencoder.ipynb in sample.ipynb, I get the following key mismatch:

__IncompatibleKeys(missing_keys=['conds_mean', 'conds_std', 'model.latent_net.time_embed.0.weight', 'model.latent_net.time_embed.0.bias', 'model.latent_net.time_embed.2.weight', 'model.latent_net.time_embed.2.bias', 'model.latent_net.layers.0.linear.weight', 'model.latent_net.layers.0.linear.bias', 'model.latent_net.layers.0.linear_emb.weight', 'model.latent_net.layers.0.linear_emb.bias', 'model.latent_net.layers.0.cond_layers.1.weight', 'model.latent_net.layers.0.cond_layers.1.bias', 'model.latent_net.layers.0.norm.weight', 'model.latent_net.layers.0.norm.bias', 'model.latent_net.layers.1.linear.weight', 'model.latent_net.layers.1.linear.bias', 'model.latent_net.layers.1.linear_emb.weight', 'model.latent_net.layers.1.linear_emb.bias', 'model.latent_net.layers.1.cond_layers.1.weight', 'model.latent_net.layers.1.cond_layers.1.bias', 'model.latent_net.layers.1.norm.weight', 'model.latent_net.layers.1.norm.bias', 'model.latent_net.layers.2.linear.weight', 'model.latent_net.layers.2.linear.bias', 'model.latent_net.layers.2.linear_emb.weight', 'model.latent_net.layers.2.linear_emb.bias', 'model.latent_net.layers.2.cond_layers.1.weight', 'model.latent_net.layers.2.cond_layers.1.bias', 'model.latent_net.layers.2.norm.weight', 'model.latent_net.layers.2.norm.bias', 'model.latent_net.layers.3.linear.weight', 'model.latent_net.layers.3.linear.bias', 'model.latent_net.layers.3.linear_emb.weight', 'model.latent_net.layers.3.linear_emb.bias', 'model.latent_net.layers.3.cond_layers.1.weight', 'model.latent_net.layers.3.cond_layers.1.bias', 'model.latent_net.layers.3.norm.weight', 'model.latent_net.layers.3.norm.bias', 'model.latent_net.layers.4.linear.weight', 'model.latent_net.layers.4.linear.bias', 'model.latent_net.layers.4.linear_emb.weight', 'model.latent_net.layers.4.linear_emb.bias', 'model.latent_net.layers.4.cond_layers.1.weight', 'model.latent_net.layers.4.cond_layers.1.bias', 'model.latent_net.layers.4.norm.weight', 'model.latent_net.layers.4.norm.bias', 'model.latent_net.layers.5.linear.weight', 'model.latent_net.layers.5.linear.bias', 'model.latent_net.layers.5.linear_emb.weight', 'model.latent_net.layers.5.linear_emb.bias', 'model.latent_net.layers.5.cond_layers.1.weight', 'model.latent_net.layers.5.cond_layers.1.bias', 'model.latent_net.layers.5.norm.weight', 'model.latent_net.layers.5.norm.bias', 'model.latent_net.layers.6.linear.weight', 'model.latent_net.layers.6.linear.bias', 'model.latent_net.layers.6.linear_emb.weight', 'model.latent_net.layers.6.linear_emb.bias', 'model.latent_net.layers.6.cond_layers.1.weight', 'model.latent_net.layers.6.cond_layers.1.bias', 'model.latent_net.layers.6.norm.weight', 'model.latent_net.layers.6.norm.bias', 'model.latent_net.layers.7.linear.weight', 'model.latent_net.layers.7.linear.bias', 'model.latent_net.layers.7.linear_emb.weight', 'model.latent_net.layers.7.linear_emb.bias', 'model.latent_net.layers.7.cond_layers.1.weight', 'model.latent_net.layers.7.cond_layers.1.bias', 'model.latent_net.layers.7.norm.weight', 'model.latent_net.layers.7.norm.bias', 'model.latent_net.layers.8.linear.weight', 'model.latent_net.layers.8.linear.bias', 'model.latent_net.layers.8.linear_emb.weight', 'model.latent_net.layers.8.linear_emb.bias', 'model.latent_net.layers.8.cond_layers.1.weight', 'model.latent_net.layers.8.cond_layers.1.bias', 'model.latent_net.layers.8.norm.weight', 'model.latent_net.layers.8.norm.bias', 'model.latent_net.layers.9.linear.weight', 'model.latent_net.layers.9.linear.bias', 'ema_model.latent_net.time_embed.0.weight', 'ema_model.latent_net.time_embed.0.bias', 'ema_model.latent_net.time_embed.2.weight', 'ema_model.latent_net.time_embed.2.bias', 'ema_model.latent_net.layers.0.linear.weight', 'ema_model.latent_net.layers.0.linear.bias', 'ema_model.latent_net.layers.0.linear_emb.weight', 'ema_model.latent_net.layers.0.linear_emb.bias', 'ema_model.latent_net.layers.0.cond_layers.1.weight', 'ema_model.latent_net.layers.0.cond_layers.1.bias', 'ema_model.latent_net.layers.0.norm.weight', 'ema_model.latent_net.layers.0.norm.bias', 'ema_model.latent_net.layers.1.linear.weight', 'ema_model.latent_net.layers.1.linear.bias', 'ema_model.latent_net.layers.1.linear_emb.weight', 'ema_model.latent_net.layers.1.linear_emb.bias', 'ema_model.latent_net.layers.1.cond_layers.1.weight', 'ema_model.latent_net.layers.1.cond_layers.1.bias', 'ema_model.latent_net.layers.1.norm.weight', 'ema_model.latent_net.layers.1.norm.bias', 'ema_model.latent_net.layers.2.linear.weight', 'ema_model.latent_net.layers.2.linear.bias', 'ema_model.latent_net.layers.2.linear_emb.weight', 'ema_model.latent_net.layers.2.linear_emb.bias', 'ema_model.latent_net.layers.2.cond_layers.1.weight', 'ema_model.latent_net.layers.2.cond_layers.1.bias', 'ema_model.latent_net.layers.2.norm.weight', 'ema_model.latent_net.layers.2.norm.bias', 'ema_model.latent_net.layers.3.linear.weight', 'ema_model.latent_net.layers.3.linear.bias', 'ema_model.latent_net.layers.3.linear_emb.weight', 'ema_model.latent_net.layers.3.linear_emb.bias', 'ema_model.latent_net.layers.3.cond_layers.1.weight', 'ema_model.latent_net.layers.3.cond_layers.1.bias', 'ema_model.latent_net.layers.3.norm.weight', 'ema_model.latent_net.layers.3.norm.bias', 'ema_model.latent_net.layers.4.linear.weight', 'ema_model.latent_net.layers.4.linear.bias', 'ema_model.latent_net.layers.4.linear_emb.weight', 'ema_model.latent_net.layers.4.linear_emb.bias', 'ema_model.latent_net.layers.4.cond_layers.1.weight', 'ema_model.latent_net.layers.4.cond_layers.1.bias', 'ema_model.latent_net.layers.4.norm.weight', 'ema_model.latent_net.layers.4.norm.bias', 'ema_model.latent_net.layers.5.linear.weight', 'ema_model.latent_net.layers.5.linear.bias', 'ema_model.latent_net.layers.5.linear_emb.weight', 'ema_model.latent_net.layers.5.linear_emb.bias', 'ema_model.latent_net.layers.5.cond_layers.1.weight', 'ema_model.latent_net.layers.5.cond_layers.1.bias', 'ema_model.latent_net.layers.5.norm.weight', 'ema_model.latent_net.layers.5.norm.bias', 'ema_model.latent_net.layers.6.linear.weight', 'ema_model.latent_net.layers.6.linear.bias', 'ema_model.latent_net.layers.6.linear_emb.weight', 'ema_model.latent_net.layers.6.linear_emb.bias', 'ema_model.latent_net.layers.6.cond_layers.1.weight', 'ema_model.latent_net.layers.6.cond_layers.1.bias', 'ema_model.latent_net.layers.6.norm.weight', 'ema_model.latent_net.layers.6.norm.bias', 'ema_model.latent_net.layers.7.linear.weight', 'ema_model.latent_net.layers.7.linear.bias', 'ema_model.latent_net.layers.7.linear_emb.weight', 'ema_model.latent_net.layers.7.linear_emb.bias', 'ema_model.latent_net.layers.7.cond_layers.1.weight', 'ema_model.latent_net.layers.7.cond_layers.1.bias', 'ema_model.latent_net.layers.7.norm.weight', 'ema_model.latent_net.layers.7.norm.bias', 'ema_model.latent_net.layers.8.linear.weight', 'ema_model.latent_net.layers.8.linear.bias', 'ema_model.latent_net.layers.8.linear_emb.weight', 'ema_model.latent_net.layers.8.linear_emb.bias', 'ema_model.latent_net.layers.8.cond_layers.1.weight', 'ema_model.latent_net.layers.8.cond_layers.1.bias', 'ema_model.latent_net.layers.8.norm.weight', 'ema_model.latent_net.layers.8.norm.bias', 'ema_model.latent_net.layers.9.linear.weight', 'ema_model.latent_net.layers.9.linear.bias'], unexpected_keys=[])_

**Comment by phizaz** [comment]
The sampling experiment has a latent DDIM network (which is `.latent_net.*`) while the autoencoding experiment doesn't.
